# -*- coding: utf-8 -*-
""".ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18wE00YuxYZ5ob8B3PBVTxk3cfaaUueea
"""

s=input()
print(s[::-1])

